/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // =============================================
        // INTERNATLAS DESIGN SYSTEM — Material Design 3
        // =============================================
        primary: {
          DEFAULT: '#00236f',
          dark: '#001a54',
          light: '#dce1ff',
          container: '#1e3a8a',
          'fixed': '#dce1ff',
          'fixed-dim': '#b6c4ff',
        },
        secondary: {
          DEFAULT: '#712ae2',
          container: '#8a4cfc',
          fixed: '#eaddff',
          'fixed-dim': '#d2bbff',
        },
        tertiary: {
          DEFAULT: '#00285e',
          container: '#003d88',
          fixed: '#d8e2ff',
          'fixed-dim': '#adc6ff',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
          light: '#FEE2E2',
        },
        surface: {
          DEFAULT: '#faf8ff',
          dim: '#d2d9f4',
          bright: '#faf8ff',
          'container-lowest': '#ffffff',
          'container-low': '#f2f3ff',
          container: '#eaedff',
          'container-high': '#e2e7ff',
          'container-highest': '#dae2fd',
          variant: '#dae2fd',
          tint: '#4059aa',
          secondary: '#F1F5F9',
        },
        background: '#faf8ff',
        outline: {
          DEFAULT: '#757682',
          variant: '#c5c5d3',
        },
        'on-primary': '#ffffff',
        'on-primary-container': '#90a8ff',
        'on-primary-fixed': '#00164e',
        'on-primary-fixed-variant': '#264191',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fffbff',
        'on-secondary-fixed': '#25005a',
        'on-secondary-fixed-variant': '#5a00c6',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#82abff',
        'on-tertiary-fixed': '#001a42',
        'on-tertiary-fixed-variant': '#004395',
        'on-surface': '#131b2e',
        'on-surface-variant': '#444651',
        'on-background': '#131b2e',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        'inverse-primary': '#b6c4ff',
        // Legacy tokens kept for compatibility
        success: { DEFAULT: '#16A34A', light: '#DCFCE7' },
        warning: { DEFAULT: '#D97706', light: '#FEF3C7' },
        info: { DEFAULT: '#0284C7', light: '#E0F2FE' },
        border: { DEFAULT: '#c5c5d3', strong: '#757682' },
        text: {
          primary: '#131b2e',
          secondary: '#444651',
          muted: '#757682',
          disabled: '#94A3B8',
        },
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'display': ['Inter', 'sans-serif'],
        'display-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'caption': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.25rem',
        'gutter-sm': '1rem',
        'gutter': '1.5rem',
        'gutter-lg': '2rem',
        'margin': '2rem',
        'margin-mobile': '1rem',
        'margin-tablet': '1.5rem',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.08), 0 2px 4px rgba(0,0,0,0.04)',
        'nav': '0 1px 8px rgba(0,0,0,0.04)',
        'dropdown': '0 8px 24px rgba(0,0,0,0.12)',
      },
      backdropBlur: {
        'xl': '24px',
      },
      animation: {
        'ping-slow': 'ping 2s cubic-bezier(0, 0, 0.2, 1) infinite',
      }
    },
  },
  plugins: [],
}
